import {CalculateMetadataFunction, staticFile} from 'remotion';
import {EpisodeData} from './types';
import {fetchEpisodeData} from './load-episode';

/**
 * Asset manifest loader + resolvers.
 *
 * public/assets/assets.json is generated by the art pipeline and lists every
 * usable image (portraits, props, loops, memes, mascots, backdrops). Files
 * NOT listed in the manifest are treated as missing — components must render
 * their house-style placeholder instead of pointing <Img> at a 404 (a failed
 * image load fails the whole render).
 *
 * Loaded once in calculateMetadata (same pattern as load-episode.ts) and
 * passed down as a plain prop — no per-frame delayRender.
 */

export type AssetKind =
  | 'portrait'
  | 'prop'
  | 'loop'
  | 'meme'
  | 'mascot'
  | 'backdrop';

export interface AssetEntry {
  id: string;
  kind: AssetKind;
  /** Path relative to public/assets/. */
  file: string;
  /** Optional transparent-background variant, relative to public/assets/. */
  alpha?: string | null;
  /** Display label (name-plate chips etc.). */
  label?: string | null;
  tags?: string[];
  /** For kind "loop": ordered frame paths relative to public/assets/. */
  loop?: string[] | null;
  note?: string;
}

export interface AssetManifest {
  assets: AssetEntry[];
}

export const EMPTY_MANIFEST: AssetManifest = {assets: []};

/** staticFile URL for a manifest-relative path. */
export const assetSrc = (path: string): string => staticFile(`assets/${path}`);

/** Best image path for an entry, preferring the alpha cutout when asked. */
export const assetFile = (entry: AssetEntry, preferAlpha = false): string =>
  preferAlpha && entry.alpha ? entry.alpha : entry.file;

export const fetchAssetManifest = async (): Promise<AssetManifest> => {
  try {
    const res = await fetch(staticFile('assets/assets.json'));
    if (!res.ok) {
      throw new Error(`assets/assets.json -> HTTP ${res.status}`);
    }
    const data = (await res.json()) as AssetManifest;
    if (!Array.isArray(data.assets)) return EMPTY_MANIFEST;
    return {assets: data.assets.filter((a) => a && a.id && a.file)};
  } catch {
    // Manifest not generated yet: every resolve misses, components fall
    // back to their placeholder cards.
    return EMPTY_MANIFEST;
  }
};

const norm = (s: string): string => s.trim().toLowerCase();

/**
 * Resolve an asset by id, label, or tag. Match priority:
 *   1. exact id  2. exact label  3. exact tag  4. id/label substring.
 * Ties break deterministically by id (lexicographic).
 */
export const resolveAsset = (
  manifest: AssetManifest | null | undefined,
  idOrTag: string,
  kind?: AssetKind,
): AssetEntry | null => {
  const q = norm(idOrTag);
  if (!q) return null;
  const pool = (manifest?.assets ?? [])
    .filter((a) => !kind || a.kind === kind)
    .slice()
    .sort((a, b) => a.id.localeCompare(b.id));
  return (
    pool.find((a) => norm(a.id) === q) ??
    pool.find((a) => norm(a.label ?? '') === q) ??
    pool.find((a) => (a.tags ?? []).some((t) => norm(t) === q)) ??
    pool.find(
      (a) => norm(a.id).includes(q) || norm(a.label ?? '').includes(q),
    ) ??
    null
  );
};

/**
 * Resolve a meme by loose intent ("this is fine", "panic button").
 * Keyword-scores intent tokens against id / tags / label / note;
 * highest score wins, ties break by id (deterministic).
 */
export const resolveMeme = (
  manifest: AssetManifest | null | undefined,
  intent: string,
): AssetEntry | null => {
  const tokens = norm(intent)
    .split(/[^a-z0-9]+/)
    .filter((t) => t.length > 1);
  if (tokens.length === 0) return null;
  const pool = (manifest?.assets ?? [])
    .filter((a) => a.kind === 'meme')
    .slice()
    .sort((a, b) => a.id.localeCompare(b.id));

  let best: AssetEntry | null = null;
  let bestScore = 0;
  for (const a of pool) {
    const id = norm(a.id);
    const tags = (a.tags ?? []).map(norm);
    const label = norm(a.label ?? '');
    const note = norm(a.note ?? '');
    let score = 0;
    for (const t of tokens) {
      if (tags.includes(t)) score += 3;
      if (id.includes(t)) score += 2;
      if (label.includes(t)) score += 1;
      if (note.includes(t)) score += 1;
    }
    // Whole-intent id match is a strong signal ("this-is-fine").
    if (id === tokens.join('-')) score += 5;
    if (score > bestScore) {
      bestScore = score;
      best = a;
    }
  }
  return best;
};

export type EpisodeAssetsProps = {
  data: EpisodeData | null;
  assets?: AssetManifest | null;
} & Record<string, unknown>;

/**
 * calculateMetadata factory: resolves episode data AND the asset manifest
 * before render (mirrors makeEpisodeMetadata in load-episode.ts).
 */
export const makeEpisodeAssetsMetadata =
  (slug: string): CalculateMetadataFunction<EpisodeAssetsProps> =>
  async ({props}) => {
    const [data, assets] = await Promise.all([
      props.data ? Promise.resolve(props.data) : fetchEpisodeData(slug),
      props.assets ? Promise.resolve(props.assets) : fetchAssetManifest(),
    ]);
    return {props: {...props, data, assets}};
  };
